version: '3.7'
services:
  website_implementation:
    image: k4liber/real-data-website:latest
    container_name: website_implementation
    environment:
      - API_URL=http://localhost:5000
    ports:
      - "3000:80"
