version: '3.7'
services:
  website:
    container_name: website
    environment:
      - API_URL='http://13.36.229.179:5000'
    build: ./website
  nginx:
    container_name: website_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - website
