version: '3.7'
services:
  website_implementation:
    container_name: website_implementation
    environment:
      - API_URL=http://localhost:5000
    build: ./website_angular
    ports:
      - "3000:80"
  nginx:
    container_name: website_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - website_implementation
